name: Generate Snake Animation

on:
  schedule:
    - cron: "0 23 * * *" # tiap malam jam 11
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout kode
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate SVG snake
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: rifki123-cell
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Push ke branch `output`
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
